import { ClipboardOutline } from "@graywolfai/react-heroicons";
import { useState } from "react";
import { v7 } from "uuid";
import { useCallStore } from "../state/call";

export const Home = () => {
  const startCall = useCallStore((state) => state.startCall);

  const [isCopied, setIsCopied] = useState(false);
  const onClickCopy = () => {
    const passphrase = document.querySelector(
      "input[name='passphrase']"
    ) as HTMLInputElement;
    navigator.clipboard.writeText(passphrase.value);

    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const onClickStart = () => {
    const passphrase = document.querySelector(
      "input[name='passphrase']"
    ) as HTMLInputElement;
    startCall(passphrase.value);
  };

  return (
    <div className="h-screen w-screen">
      <div className="h-full flex flex-col bg-gray-300 rounded-md items-center justify-center gap-2">
        <div className="mb-20 flex flex-col items-center justify-center w-[80%]">
          <span className="text-3xl">
            Share a passphrase with a friend and start video chatting
          </span>
          <span className="text-sm italic">
            (use the default passphrase if you don't want to join strangers or
            be joined by strangers)
          </span>
        </div>
        <div className="flex flex-col items-center justify-center gap-2 w-[80%]">
          <span>Autogenerated phrase:</span>
          <div className="flex gap-2 w-full justify-center">
            <input
              type="text"
              name="passphrase"
              defaultValue={v7()}
              className="rounded-sm w-[100%] md:w-[55%] lg:w-[33%]"
            />
            <button
              name="copy"
              className="p-1 h-7 flex items-center bg-gray-500 rounded-lg active:bg-gray-700"
              onClick={onClickCopy}
            >
              {isCopied ? "Copied!" : <ClipboardOutline className="h-5 w-5" />}
            </button>
          </div>
        </div>
        <div>
          <button
            name="start"
            onClick={onClickStart}
            className="p-3 hover:px-4 mt-10 bg-gray-500 rounded-lg active:bg-gray-700 text-2xl"
          >
            Start
          </button>
        </div>
      </div>
    </div>
  );
};
